displayName=Advanced Hp Bar
author=github.com/chrisreydev
description=Configure hp bar to display numbers, prayer points, special attack, and more. Adjust hp bar style.
tags=hp,advanced hp bar, hitpoints, prayer, hitpoints bar, combat, overlay, configurable hp bar
plugins=com.advancedhpbar.AdvancedHpBarPlugin